### ISSUE TITLE
timestamp fields are converted to numbers

### ISSUE THREAD

**Issue by kranthikandi** [codingchili/excelastic#1]
i have a timestamp field in this format "4/14/2016 20:32". but i see the values in number format "42,972" in kibana 4.5.*.
how do i format this field to "April 14 2016" or any other timestamp format.

@codingchili

**Comment by codingchili** [comment]
There is an issue with the parsing of Excel files. Only Numeric and String fields are parsed properly. The issue is present in [this method](https://github.com/codingchili/parser-excel-elasticsearch/blob/master/src/main/java/Model/FileParser.java#L92), where date type fields are not handled properly.

Set the type of the date fields in Excel to Text/String when using release 1.0.0 and it should work whenever the format is recognized by ElasticSearch. 

Thank you for submitting this issue @kranthikandi .

**Comment by codingchili** [comment]
There is an issue with the parsing of dates. Cells that contains string values strip everything after the first '/', any dates containing that character are therefore misinterpreted.

The issue exists at [this line](https://github.com/codingchili/parser-excel-elasticsearch/blob/master/src/main/java/Model/FileParser.java#L102).

Try change the slashes for dashes until it is fixed.

Thank you for submitting this issue @kranthikandi .

**Comment by kranthikandi** [comment]
I have tried that yet, but i am closing this issue. Thank you
