### ISSUE TITLE
Import new data into same index?

### ISSUE THREAD

**Issue by ando01** [codingchili/excelastic#45]
Hi Chili,

Thanks for the great plugin. I have it working well to import some excel data into our ELK stack and generate reports. One question I had was is there a way to take updated data from that same spreadsheet and import it into the same index without having to create another index? Our report graphs are built from the main index and it would break them if I had to create a new index every time the data is updated.

Thanks,
Andy

**Comment by codingchili** [comment]
Hello!

If I understand correctly, you want to update already indexed rows and have these changes reflected in elasticsearch? This is currently not supported.

To update existing rows instead of duplicating, each row must be uniquely identifiable.

I have two proposals to add this feature.

a) Providing a column with the title/name of "@id" or "_id" that can be used when indexing the document.
- requires updating existing entries, not as simple as just indexing.
- requires modifications to excel files.
- supports partial updates (for example importing an excel file with a subset of entries.)

b) an option to clear the index before starting the import.
- easy to integrate as an option to the command line and web interface.
- no modifications to the excel files are needed. 
- only supports partial updates where documents are strictly distinct.

Regarding performance and indexing time both methods should be roughly equal. In option A all objects must be sent to the server, if it exists it must be overwritten and re-indexed anyways. 

Could you elaborate a bit on your use case? I'm wondering if its absolutely necessary to update old entries. It would be simpler to add updated data to the end of the file and use the row offset feature, or split the changes into a new file and import into the same index without creating duplicates.

Thanks for submitting an issue

**Comment by ando01** [comment]
Hi and thanks for the quick reply. I think option B would be the best as it would not require modification to the excel file. The use case scenario is we have a main spreadsheet that gets updated weekly with new information. I would like to import only the changes and not create any duplicates. I think option B would be the best for this.

**Comment by codingchili** [comment]
Hello again,

I'll add a moderate amount of priority to this task. Expect a new release with this feature added within 8 days. I will be adding an option to use basic authentication as well in the next release.

Regards

**Comment by ando01** [comment]
Great! Thank You!!

**Comment by codingchili** [comment]
Fixed in latest release: https://github.com/codingchili/parser-excel-elasticsearch/releases/tag/1.2.4
