### ISSUE TITLE
Integer changed from # to #.0, example: changed from 2 to 2.0 

### ISSUE THREAD

**Issue by foxericlee** [codingchili/excelastic#85]
A Column is a integer, just like 1, 2 or etc. But when I load into elasticsearch. The integer had changed from integer to float, like 1.0, 2.0 or etc. How can I do?

**Comment by foxericlee** [comment]
Maybe convert should be controlled by excel column's type. But I try, it dose not work.

**Comment by codingchili** [comment]
Hmm might be because it's not possible to differentiate between the two using the cell type ? Cell type numeric matches both if I remember correctly. 

There was an issue before with mixed field types float/int, so maybe we just chose to use floats for everything. As it "doesn't matter" for visualizations..

**Comment by codingchili** [comment]
If I can get a hold of Excel I could try this. I'm guessing there are more specific cell types than NUMERIC to match on to differentiate integer and floats.

**Comment by codingchili** [comment]
For numeric cells in Excel, the value will be treated as an integer if the decimal point is zero.

3.0 => 3 (integer)
3.14 => 3.14 (float)

Note that this could cause type inference to fail for int/float if the first data row contains the value 3.0 and the next 3.14.

This behavior is included in 1.3.8, please reopen if this is still an issue.
